# Generated by Django 3.2.25 on 2025-04-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0003_auto_20250423_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='Rate',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_x2_slots',
            field=models.SmallIntegerField(default=0),
        ),
    ]
