# Generated by Django 3.2.25 on 2025-04-26 09:09

import PcPart.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('PcPart', '0005_part_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='part',
            name='image_filename',
            field=models.ImageField(blank=True, null=True, upload_to=PcPart.models.imageSaver),
        ),
    ]
