# Generated by Django 3.2.25 on 2025-04-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0007_alter_part_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OS',
        ),
    ]
