# Generated by Django 3.2.25 on 2025-05-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0008_delete_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
