# Generated by Django 3.2.25 on 2025-05-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0009_part_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='xmp_support',
            new_name='Extreme_Memory_Profile_support',
        ),
        migrations.RenameField(
            model_name='opticaldrive',
            old_name='bd',
            new_name='blu_ray_read_speed',
        ),
        migrations.RenameField(
            model_name='opticaldrive',
            old_name='bd_write',
            new_name='blu_ray_write_speed',
        ),
        migrations.RenameField(
            model_name='opticaldrive',
            old_name='cd',
            new_name='cd_read_speed',
        ),
        migrations.RenameField(
            model_name='opticaldrive',
            old_name='cd_write',
            new_name='cd_write_speed',
        ),
        migrations.RenameField(
            model_name='opticaldrive',
            old_name='dvd',
            new_name='dvd_read_speed',
        ),
        migrations.RenameField(
            model_name='opticaldrive',
            old_name='dvd_write',
            new_name='dvd_write_speed',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='Gid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='liked',
            new_name='like_count',
        ),
    ]
