# Generated by Django 3.2.25 on 2025-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0010_auto_20250504_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='in_storage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='like_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
