# Generated by Django 3.2.25 on 2025-05-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0011_auto_20250504_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='id',
            new_name='Gid',
        ),
    ]
