# Generated by Django 3.2.25 on 2025-05-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0012_rename_id_part_gid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='Gid',
            new_name='id',
        ),
    ]
