# Generated by Django 3.2.25 on 2025-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0013_rename_gid_part_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='radiator_support',
            field=models.ManyToManyField(blank=True, null=True, to='PcPart.Radiator_size'),
        ),
    ]
