# Generated by Django 3.2.25 on 2025-05-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0015_auto_20250512_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='comatiple_motherboard',
            field=models.ManyToManyField(to='PcPart.motherBoard_Socket'),
        ),
        migrations.AlterField(
            model_name='casefan',
            name='size',
            field=models.IntegerField(choices=[(40, '40mm'), (50, '50mm'), (60, '60mm'), (70, '70mm'), (80, '80mm'), (90, '90mm'), (92, '92mm'), (95, '95mm'), (120, '120mm'), (140, '140mm'), (180, '180mm'), (193, '193mm'), (200, '200mm'), (220, '220mm'), (230, '230mm'), (240, '240mm'), (250, '250mm'), (280, '280mm')]),
        ),
        migrations.AlterField(
            model_name='cpucooler',
            name='size',
            field=models.IntegerField(choices=[(40, '40mm'), (50, '50mm'), (60, '60mm'), (70, '70mm'), (80, '80mm'), (90, '90mm'), (92, '92mm'), (95, '95mm'), (120, '120mm'), (140, '140mm'), (180, '180mm'), (193, '193mm'), (200, '200mm'), (220, '220mm'), (230, '230mm'), (240, '240mm'), (250, '250mm'), (280, '280mm')]),
        ),
    ]
