# Generated by Django 3.2.25 on 2025-05-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0016_auto_20250513_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='m2_slut',
            new_name='m2_slot',
        ),
    ]
