# Generated by Django 3.2.25 on 2025-05-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0017_rename_m2_slut_motherboard_m2_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocard',
            old_name='comatiple_motherboard',
            new_name='compatible_motherboard',
        ),
    ]
