# Generated by Django 3.2.25 on 2025-05-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0018_rename_comatiple_motherboard_videocard_compatible_motherboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='pcie_x16_slots',
            new_name='pcie_slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pci_slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pcie_x1_slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pcie_x2_slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pcie_x4_slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pcie_x8_slots',
        ),
    ]
