# Generated by Django 3.2.25 on 2025-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0019_auto_20250514_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='generation',
            field=models.CharField(choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR3L', 'DDR3L'), ('DDR4', 'DDR4'), ('DDR4L', 'DDR4L'), ('DDR5', 'DDR5'), ('LPDDR', 'LPDDR'), ('LPDDR2', 'LPDDR2'), ('LPDDR3', 'LPDDR3'), ('LPDDR4', 'LPDDR4'), ('LPDDR4X', 'LPDDR4X'), ('LPDDR5', 'LPDDR5'), ('LPDDR5X', 'LPDDR5X')], default='DDR3', max_length=10),
        ),
    ]
