# Generated by Django 3.2.25 on 2025-05-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0020_alter_memory_generation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocard',
            old_name='power_requirement',
            new_name='old_power_requirement',
        ),
        migrations.RemoveField(
            model_name='caseaccessory',
            name='power_requirement',
        ),
        migrations.AddField(
            model_name='part',
            name='power_requirement',
            field=models.FloatField(default=0.0),
        ),
    ]
