# Generated by Django 3.2.25 on 2025-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0022_auto_20250518_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='efficiency',
            field=models.CharField(choices=[('Unrated', 'Unrated'), ('Plus', 'Plus'), ('Bronze', 'Bronze'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Titanium', 'Titanium')], default='Plus', max_length=50),
        ),
    ]
