# Generated by Django 3.2.25 on 2025-06-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0023_alter_powersupply_efficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory_Frequencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='psu',
            field=models.CharField(default='Not Included', max_length=50),
        ),
        migrations.AddField(
            model_name='memory',
            name='new_speed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PcPart.memory_frequencies'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='memory_frequencies',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='PcPart.Memory_Frequencies'),
        ),
    ]
