# Generated by Django 3.2.25 on 2025-06-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0025_remove_memory_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='new_speed',
            new_name='speed',
        ),
    ]
