# Generated by Django 3.2.25 on 2025-06-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0026_rename_new_speed_memory_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='supported_memory_frequencies',
        ),
    ]
