# Generated by Django 3.2.25 on 2025-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0027_remove_motherboard_supported_memory_frequencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='memory_frequencies',
            new_name='supported_memory_frequencies',
        ),
    ]
