# Generated by Django 3.2.25 on 2025-06-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0028_rename_memory_frequencies_motherboard_supported_memory_frequencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='speed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcPart.memory_frequencies'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='supported_memory_frequencies',
            field=models.ManyToManyField(to='PcPart.Memory_Frequencies'),
        ),
    ]
