# Generated by Django 3.2.25 on 2025-06-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0029_auto_20250602_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirelessnetworkcard',
            name='interface',
            field=models.CharField(default='PCIe x1', max_length=20),
        ),
        migrations.AlterField(
            model_name='wiresnetworkcard',
            name='interface',
            field=models.CharField(default='PCIe x1', max_length=20),
        ),
    ]
