# Generated by Django 3.2.25 on 2025-03-08 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('perment', 'perment'), ('descount', 'descount'), ('offer', 'offer'), ('update annuncement', 'update annuncement')], default='perment', max_length=50)),
                ('title', models.CharField(default='perment!!!', max_length=50)),
                ('description', models.TextField()),
                ('descount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.descount')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.offer')),
            ],
        ),
    ]
