# Generated by Django 3.2.25 on 2025-03-08 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PcPart', '0007_auto_20250227_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBascet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_cost', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Waiting', 'Waiting'), ('Ready', 'Ready'), ('Done', 'Done'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Waiting', max_length=50)),
                ('bascet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shopbascet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcPart.part')),
            ],
        ),
        migrations.CreateModel(
            name='offer_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcPart.part')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='new offer', max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('units', models.ManyToManyField(to='home.offer_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Descount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('is_quantity_limit', models.BooleanField()),
                ('is_dated_limit', models.BooleanField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PcPart.part')),
            ],
        ),
    ]
