# Generated by Django 3.2.25 on 2025-04-13 09:03

import UserProfile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BMBC_coins', models.IntegerField()),
                ('total_paied', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(upload_to=UserProfile.models.imgprofileSave)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
