# Generated by Django 3.2.25 on 2025-04-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20250422_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='NickName',
        ),
    ]
