# Generated by Django 3.2.25 on 2025-04-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_editing',
            field=models.SmallIntegerField(default=1),
        ),
    ]
