# Generated by Django 3.2.25 on 2025-06-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0024_alter_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_paied',
            new_name='total_paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username_editing',
        ),
    ]
