# Generated by Django 3.2.25 on 2025-04-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbascet',
            name='compitability',
        ),
    ]
