# Generated by Django 3.2.25 on 2025-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_remove_shopbascet_compitability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbascet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
