# Generated by Django 3.2.25 on 2025-04-26 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_shopbascet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bascet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Cart.shopbascet'),
        ),
    ]
