# Generated by Django 3.2.25 on 2025-04-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0007_alter_part_content_type'),
        ('Cart', '0004_alter_order_bascet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Descount',
            new_name='Discount',
        ),
    ]
