# Generated by Django 3.2.25 on 2025-04-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PcPart', '0007_alter_part_content_type'),
        ('Cart', '0005_rename_descount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PcPart.part'),
        ),
    ]
