# Generated by Django 3.2.25 on 2025-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_alter_discount_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='new_price',
            field=models.FloatField(default=0.0),
        ),
    ]
