# Generated by Django 3.2.25 on 2025-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_discount_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
