# Generated by Django 3.2.25 on 2025-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_discount_remaining_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_dated_limit',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_quantity_limit',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
