# Generated by Django 3.2.25 on 2025-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbascet',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
