# Generated by Django 3.2.25 on 2025-04-28 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0011_alter_shopbascet_total_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopBascet',
            new_name='ShopBasket',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bascet',
            new_name='basket',
        ),
    ]
