# Generated by Django 3.2.25 on 2025-06-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0013_rename_shopbasket_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='state',
            new_name='statue',
        ),
    ]
