# Generated by Django 3.2.25 on 2025-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0014_rename_state_cart_statue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='team_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
