# Generated by Django 3.2.25 on 2025-06-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_cart_team_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='statue',
            new_name='status',
        ),
    ]
